on: [push]

jobs:
  get-current-branch-job:
    runs-on: ubuntu-latest
    name: Test action
    steps:
    - uses: actions/checkout@v7
    - name: Use action
      id: get-branch
      uses: ./
    - name: Echo outputs
      run: echo "name=${{ steps.get-branch.outputs.branch }} - tag=${{ steps.get-branch.outputs.tag }}"
